settings:
  auth:
    twilioapi: ""
  github:
    token: ""
  email:
    to: zinalacina@gmail.com
    from: zlacina@monbili.com
    subject: "Subject of the pull request"
    sendGridApi: ""
  repo:
    user: zinalacina
    name: github-track